# web-admin.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: csdha-web-admin
spec:
  template:
    spec:
      containers:
      - name: web-admin
        image: localhost/laravel-web:1.0
        ports:
        - containerPort: 80
          hostPort: 8002
        env:
        - name: WEB_TYPE
          value: admin
        volumeMounts:
        - name: web-storage
          mountPath: /var/www/app/storage/app
      volumes:
      - name: web-storage 
        persistentVolumeClaim:
          claimName: csdha-web-storage

